# Generated by Django 4.1.5 on 2023-01-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Outage',
        ),
    ]
