# Generated by Django 4.1.5 on 2023-01-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outages', '0003_outage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outage',
            name='location',
            field=models.TextField(),
        ),
    ]
